apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: helpdesk
data:
  FRONTEND_BASE_URL: "http://frontend-helpdesk.apps.example.com"
  PORT: "3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailer-config
  namespace: helpdesk
data:
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
  SMTP_FROM: "noreply@helpdesk.local"
  POLL_INTERVAL_MS: "5000"
